# Generated by Django 5.2.6 on 2025-09-15 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='owner',
            fields=[
                ('Model', models.CharField(max_length=10)),
                ('car_no', models.IntegerField(primary_key=True, serialize=False)),
                ('quality', models.CharField(max_length=10)),
                ('year_prod', models.IntegerField()),
                ('colour', models.CharField(max_length=10)),
            ],
        ),
    ]
