# Generated by Django 5.2.6 on 2025-09-29 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('car_model', models.CharField(max_length=10)),
                ('plate_no', models.IntegerField(primary_key=True, serialize=False)),
                ('car_color', models.CharField(max_length=10)),
                ('price', models.IntegerField()),
                ('Adharno', models.IntegerField()),
            ],
        ),
    ]
